// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package cn.iocoder.springboot.lab64.userservice.api;

public interface UserGetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.iocoder.springboot.lab64.userservice.api.UserGetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
