// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package cn.iocoder.springcloud.labx30.userservice.api;

public interface UserGetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.iocoder.springcloud.labx30.userservice.cn.iocoder.springcloud.labx30.userservice.api.UserGetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   */
  String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 gender = 3;</code>
   */
  int getGender();
}
