// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package cn.iocoder.springcloud.labx30.userservice.api;

public interface UserGetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.iocoder.springcloud.labx30.userservice.cn.iocoder.springcloud.labx30.userservice.api.UserGetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
