// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package cn.iocoder.springcloud.labx30.userservice.api;

/**
 * Protobuf type {@code cn.iocoder.springcloud.labx30.userservice.cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse}
 */
public  final class UserCreateResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cn.iocoder.springcloud.labx30.userservice.cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse)
        UserCreateResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserCreateResponse.newBuilder() to construct.
  private UserCreateResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserCreateResponse() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserCreateResponse();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserCreateResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.iocoder.springcloud.labx30.userservice.api.UserServiceOuterClass.internal_static_cn_iocoder_springcloud_labx30_userservice_api_UserCreateResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.iocoder.springcloud.labx30.userservice.api.UserServiceOuterClass.internal_static_cn_iocoder_springcloud_labx30_userservice_api_UserCreateResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse.class, cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse)) {
      return super.equals(obj);
    }
    cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse other = (cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse) obj;

    if (getId()
        != other.getId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cn.iocoder.springcloud.labx30.userservice.cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cn.iocoder.springcloud.labx30.userservice.cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse)
      cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.iocoder.springcloud.labx30.userservice.api.UserServiceOuterClass.internal_static_cn_iocoder_springcloud_labx30_userservice_api_UserCreateResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.iocoder.springcloud.labx30.userservice.api.UserServiceOuterClass.internal_static_cn_iocoder_springcloud_labx30_userservice_api_UserCreateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse.class, cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse.Builder.class);
    }

    // Construct using cn.iocoder.springcloud.labx30.userservice.cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.iocoder.springcloud.labx30.userservice.api.UserServiceOuterClass.internal_static_cn_iocoder_springcloud_labx30_userservice_api_UserCreateResponse_descriptor;
    }

    @Override
    public cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    @Override
    public cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse build() {
      cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse buildPartial() {
      cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse result = new cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse(this);
      result.id_ = id_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse) {
        return mergeFrom((cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse other) {
      if (other == getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cn.iocoder.springcloud.labx30.userservice.cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse)
  }

  // @@protoc_insertion_point(class_scope:cn.iocoder.springcloud.labx30.userservice.cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse)
  private static final cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse();
  }

  public static cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserCreateResponse>
      PARSER = new com.google.protobuf.AbstractParser<UserCreateResponse>() {
    @Override
    public UserCreateResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserCreateResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserCreateResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<UserCreateResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public cn.iocoder.springcloud.labx30.userservice.api.UserCreateResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

