// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package cn.iocoder.springboot.lab64.userservice.api;

public interface UserCreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.iocoder.springboot.lab64.userservice.api.UserCreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 gender = 2;</code>
   */
  int getGender();
}
