// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package cn.iocoder.springboot.lab64.userservice.api;

public final class UserServiceOuterClass {
  private UserServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_iocoder_springboot_lab64_userservice_api_UserGetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_iocoder_springboot_lab64_userservice_api_UserGetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_iocoder_springboot_lab64_userservice_api_UserGetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_iocoder_springboot_lab64_userservice_api_UserGetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_iocoder_springboot_lab64_userservice_api_UserCreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_iocoder_springboot_lab64_userservice_api_UserCreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_iocoder_springboot_lab64_userservice_api_UserCreateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_iocoder_springboot_lab64_userservice_api_UserCreateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021UserService.proto\022+cn.iocoder.springbo" +
      "ot.lab64.userservice.api\"\034\n\016UserGetReque" +
      "st\022\n\n\002id\030\001 \001(\005\";\n\017UserGetResponse\022\n\n\002id\030" +
      "\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\016\n\006gender\030\003 \001(\005\"1\n\021U" +
      "serCreateRequest\022\014\n\004name\030\001 \001(\t\022\016\n\006gender" +
      "\030\002 \001(\005\" \n\022UserCreateResponse\022\n\n\002id\030\001 \001(\005" +
      "2\234\002\n\013UserService\022\200\001\n\003get\022;.cn.iocoder.sp" +
      "ringboot.lab64.userservice.api.UserGetRe" +
      "quest\032<.cn.iocoder.springboot.lab64.user" +
      "service.api.UserGetResponse\022\211\001\n\006create\022>" +
      ".cn.iocoder.springboot.lab64.userservice" +
      ".api.UserCreateRequest\032?.cn.iocoder.spri" +
      "ngboot.lab64.userservice.api.UserCreateR" +
      "esponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cn_iocoder_springboot_lab64_userservice_api_UserGetRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_iocoder_springboot_lab64_userservice_api_UserGetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_iocoder_springboot_lab64_userservice_api_UserGetRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_cn_iocoder_springboot_lab64_userservice_api_UserGetResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_iocoder_springboot_lab64_userservice_api_UserGetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_iocoder_springboot_lab64_userservice_api_UserGetResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Gender", });
    internal_static_cn_iocoder_springboot_lab64_userservice_api_UserCreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cn_iocoder_springboot_lab64_userservice_api_UserCreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_iocoder_springboot_lab64_userservice_api_UserCreateRequest_descriptor,
        new java.lang.String[] { "Name", "Gender", });
    internal_static_cn_iocoder_springboot_lab64_userservice_api_UserCreateResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_cn_iocoder_springboot_lab64_userservice_api_UserCreateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_iocoder_springboot_lab64_userservice_api_UserCreateResponse_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
