server:
  port: 9091


spring:
  # datasource 数据源配置内容
  datasource:
    url: jdbc:mysql://192.168.4.71:3306/lab-test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
